[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.31.0"
ci = ["github"]
installers = ["shell", "homebrew"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
]
packages = ["voss-cli"]
tap = "voss-lang/homebrew-tap"
publish-jobs = ["homebrew"]
pr-run-mode = "plan"
install-path = "~/.local/bin"
install-updater = false
checksum = "sha256"

[dist.github-custom-runners]
aarch64-apple-darwin = "macos-14"
x86_64-apple-darwin = "macos-13"
