// Package voss is the Go client SDK for a local/headless `voss serve` process.
//
// It provides generated contract types (types.gen.go), a hand-written REST
// client, a hand-parsed SSE event consumer, child-process supervision, and
// spawn/attach constructors. See the per-file documentation for details.
//
// # Type generation
//
// types.gen.go is generated by oapi-codegen from the committed OpenAPI snapshot
// at contracts/openapi.json (owned by V13.1). The types are CHECKED IN
// (CONTEXT D-06): the package builds and is inspectable without re-running
// codegen, and the drift gate (internal/drift) re-runs codegen and asserts the
// committed file is byte-identical.
//
// Codegen runs through the in-SDK normalizer (internal/specgen) rather than
// invoking oapi-codegen directly: FastAPI emits OpenAPI 3.1.0, which
// oapi-codegen v2.7.1 cannot parse, so specgen performs a deterministic
// 3.1->3.0 downgrade before delegating to the pinned `go tool oapi-codegen`.
// specgen reads contracts/openapi.json when present, else the captured
// testdata/openapi.fixture.json fallback. The upstream contract is never
// modified.
//
//go:generate go run ./internal/specgen
package voss
