// Package voss is the Go client SDK for a local/headless `voss serve` process:
// generated contract types (types.gen.go), a REST client, an SSE event
// consumer, and spawn/attach constructors.
//
// # Type generation
//
// types.gen.go is generated by oapi-codegen from contracts/openapi.json and
// CHECKED IN; the drift gate (internal/drift) re-runs codegen and asserts the
// committed file is byte-identical.
//
// Codegen runs through internal/specgen, which downgrades FastAPI's OpenAPI
// 3.1.0 to 3.0 (oapi-codegen v2.7.1 cannot parse 3.1) before delegating to the
// pinned `go tool oapi-codegen`. specgen reads contracts/openapi.json, else the
// testdata/openapi.fixture.json fallback. The upstream contract is never modified.
//
//go:generate go run ./internal/specgen
package voss
