// Package voss provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package voss

import (
	"encoding/json"
	"errors"

	"github.com/oapi-codegen/runtime"
)

// Defines values for BudgetUpdatedUnit.
const (
	Tokens BudgetUpdatedUnit = "tokens"
	Usd    BudgetUpdatedUnit = "usd"
)

// Valid indicates whether the value is a known member of the BudgetUpdatedUnit enum.
func (e BudgetUpdatedUnit) Valid() bool {
	switch e {
	case Tokens:
		return true
	case Usd:
		return true
	default:
		return false
	}
}

// Alternative defines model for Alternative.
type Alternative struct {
	Probability float32 `json:"probability"`
	Text        string  `json:"text"`
}

// BannerEvent defines model for BannerEvent.
type BannerEvent struct {
	Cwd   string `json:"cwd"`
	Git   string `json:"git"`
	Model string `json:"model"`
	Type  string `json:"type"`
	V     *int   `json:"v,omitempty"`
}

// BudgetUpdated defines model for BudgetUpdated.
type BudgetUpdated struct {
	Limit     float32            `json:"limit"`
	Remaining float32            `json:"remaining"`
	SessionId string             `json:"session_id"`
	Spent     float32            `json:"spent"`
	Type      string             `json:"type"`
	Unit      *BudgetUpdatedUnit `json:"unit,omitempty"`
	V         *int               `json:"v,omitempty"`
}

// BudgetUpdatedUnit defines model for BudgetUpdated.Unit.
type BudgetUpdatedUnit string

// ClarifyEvent defines model for ClarifyEvent.
type ClarifyEvent struct {
	Confidence float32 `json:"confidence"`
	Question   string  `json:"question"`
	Type       string  `json:"type"`
	V          *int    `json:"v,omitempty"`
}

// CognitionLoaded defines model for CognitionLoaded.
type CognitionLoaded struct {
	ArchitectureTokens int    `json:"architecture_tokens"`
	ConstraintsCount   int    `json:"constraints_count"`
	DecisionsLoaded    *int   `json:"decisions_loaded,omitempty"`
	PlansLoaded        *int   `json:"plans_loaded,omitempty"`
	Type               string `json:"type"`
	V                  *int   `json:"v,omitempty"`
}

// CognitionOverflow defines model for CognitionOverflow.
type CognitionOverflow struct {
	ArchitectureTokens int    `json:"architecture_tokens"`
	Budget             *int   `json:"budget,omitempty"`
	Type               string `json:"type"`
	V                  *int   `json:"v,omitempty"`
}

// ConfidenceUpdated defines model for ConfidenceUpdated.
type ConfidenceUpdated struct {
	MessageId *string `json:"message_id,omitempty"`
	Score     float32 `json:"score"`
	SessionId string  `json:"session_id"`
	Type      string  `json:"type"`
	V         *int    `json:"v,omitempty"`
}

// CreateSessionBody defines model for CreateSessionBody.
type CreateSessionBody struct {
	Auth     *string `json:"auth,omitempty"`
	Cwd      *string `json:"cwd,omitempty"`
	Model    *string `json:"model,omitempty"`
	ParentID *string `json:"parentID,omitempty"`
	Resume   *string `json:"resume,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// EventEnvelope OpenAPI schema anchor (H1.14).
//
// Forced into the OpenAPI components so a typed client codegens a tagged
// enum over the full event union, even though no route returns it directly.
type EventEnvelope struct {
	Event EventEnvelope_Event `json:"event"`
}

// EventEnvelope_Event defines model for EventEnvelope.Event.
type EventEnvelope_Event struct {
	union json.RawMessage
}

// FinalEvent defines model for FinalEvent.
type FinalEvent struct {
	Confidence float32 `json:"confidence"`
	CostUsd    float32 `json:"cost_usd"`
	Text       string  `json:"text"`
	Type       string  `json:"type"`
	V          *int    `json:"v,omitempty"`
}

// GateUpdated defines model for GateUpdated.
type GateUpdated struct {
	Decision  string `json:"decision"`
	Gate      string `json:"gate"`
	SessionId string `json:"session_id"`
	Type      string `json:"type"`
	V         *int   `json:"v,omitempty"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// MessageBody defines model for MessageBody.
type MessageBody struct {
	Mode  *string        `json:"mode,omitempty"`
	Parts *[]MessagePart `json:"parts,omitempty"`
}

// MessagePart defines model for MessagePart.
type MessagePart struct {
	Text *string `json:"text,omitempty"`
	Type *string `json:"type,omitempty"`
}

// PermissionReply defines model for PermissionReply.
type PermissionReply struct {
	Choice string `json:"choice"`
	Id     string `json:"id"`
}

// PermissionUpdated defines model for PermissionUpdated.
type PermissionUpdated struct {
	Args      *map[string]interface{} `json:"args,omitempty"`
	Dimension *string                 `json:"dimension,omitempty"`
	Id        string                  `json:"id"`
	ToolName  string                  `json:"tool_name"`
	Type      string                  `json:"type"`
	V         *int                    `json:"v,omitempty"`
}

// PlanEvent defines model for PlanEvent.
type PlanEvent struct {
	Confidence float32     `json:"confidence"`
	CostUsd    float32     `json:"cost_usd"`
	Steps      *[]PlanStep `json:"steps,omitempty"`
	Type       string      `json:"type"`
	V          *int        `json:"v,omitempty"`
}

// PlanStep defines model for PlanStep.
type PlanStep struct {
	Args *map[string]interface{} `json:"args,omitempty"`
	Name string                  `json:"name"`
}

// PrinciplesOverflow defines model for PrinciplesOverflow.
type PrinciplesOverflow struct {
	Budget           *int   `json:"budget,omitempty"`
	PrinciplesTokens int    `json:"principles_tokens"`
	Type             string `json:"type"`
	V                *int   `json:"v,omitempty"`
}

// ProbableEvent defines model for ProbableEvent.
type ProbableEvent struct {
	Alternatives *[]Alternative `json:"alternatives,omitempty"`
	Probability  float32        `json:"probability"`
	Text         string         `json:"text"`
	Type         string         `json:"type"`
	V            *int           `json:"v,omitempty"`
}

// ServerConnected defines model for ServerConnected.
type ServerConnected struct {
	Type string `json:"type"`
	V    *int   `json:"v,omitempty"`
}

// SessionIdle defines model for SessionIdle.
type SessionIdle struct {
	SessionId string `json:"session_id"`
	Type      string `json:"type"`
	V         *int   `json:"v,omitempty"`
}

// StatusEvent defines model for StatusEvent.
type StatusEvent struct {
	CostUsd float32 `json:"cost_usd"`
	CtxPct  float32 `json:"ctx_pct"`
	Model   string  `json:"model"`
	Tokens  int     `json:"tokens"`
	Type    string  `json:"type"`
	V       *int    `json:"v,omitempty"`
}

// StreamDelta defines model for StreamDelta.
type StreamDelta struct {
	Text string `json:"text"`
	Type string `json:"type"`
	V    *int   `json:"v,omitempty"`
}

// StreamFinalize defines model for StreamFinalize.
type StreamFinalize struct {
	Confidence *float32 `json:"confidence,omitempty"`
	CostUsd    *float32 `json:"cost_usd,omitempty"`
	Role       string   `json:"role"`
	Timestamp  *string  `json:"timestamp,omitempty"`
	Type       string   `json:"type"`
	V          *int     `json:"v,omitempty"`
}

// ThinkingEvent defines model for ThinkingEvent.
type ThinkingEvent struct {
	Label string `json:"label"`
	Type  string `json:"type"`
	V     *int   `json:"v,omitempty"`
}

// ToolEvent defines model for ToolEvent.
type ToolEvent struct {
	Args    *map[string]interface{} `json:"args,omitempty"`
	Name    string                  `json:"name"`
	State   string                  `json:"state"`
	Summary *string                 `json:"summary,omitempty"`
	Type    string                  `json:"type"`
	V       *int                    `json:"v,omitempty"`
}

// UserEvent defines model for UserEvent.
type UserEvent struct {
	Task string `json:"task"`
	Type string `json:"type"`
	V    *int   `json:"v,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// WarningEvent defines model for WarningEvent.
type WarningEvent struct {
	Message string `json:"message"`
	Type    string `json:"type"`
	V       *int   `json:"v,omitempty"`
}

// DoctorDoctorGetParams defines parameters for DoctorDoctorGet.
type DoctorDoctorGetParams struct {
	Auth *string `form:"auth,omitempty" json:"auth,omitempty"`
	Cwd  *string `form:"cwd,omitempty" json:"cwd,omitempty"`
}

// ListSavedSessionsSessionsSavedGetParams defines parameters for ListSavedSessionsSessionsSavedGet.
type ListSavedSessionsSessionsSavedGetParams struct {
	Cwd *string `form:"cwd,omitempty" json:"cwd,omitempty"`
}

// CreateSessionSessionPostJSONRequestBody defines body for CreateSessionSessionPost for application/json ContentType.
type CreateSessionSessionPostJSONRequestBody = CreateSessionBody

// PostMessageSessionSessionIdMessagePostJSONRequestBody defines body for PostMessageSessionSessionIdMessagePost for application/json ContentType.
type PostMessageSessionSessionIdMessagePostJSONRequestBody = MessageBody

// ReplyPermissionSessionSessionIdPermissionPostJSONRequestBody defines body for ReplyPermissionSessionSessionIdPermissionPost for application/json ContentType.
type ReplyPermissionSessionSessionIdPermissionPostJSONRequestBody = PermissionReply

// AsServerConnected returns the union data inside the EventEnvelope_Event as a ServerConnected
func (t EventEnvelope_Event) AsServerConnected() (ServerConnected, error) {
	var body ServerConnected
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerConnected overwrites any union data inside the EventEnvelope_Event as the provided ServerConnected
func (t *EventEnvelope_Event) FromServerConnected(v ServerConnected) error {
	v.Type = "server.connected"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerConnected performs a merge with any union data inside the EventEnvelope_Event, using the provided ServerConnected
func (t *EventEnvelope_Event) MergeServerConnected(v ServerConnected) error {
	v.Type = "server.connected"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSessionIdle returns the union data inside the EventEnvelope_Event as a SessionIdle
func (t EventEnvelope_Event) AsSessionIdle() (SessionIdle, error) {
	var body SessionIdle
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionIdle overwrites any union data inside the EventEnvelope_Event as the provided SessionIdle
func (t *EventEnvelope_Event) FromSessionIdle(v SessionIdle) error {
	v.Type = "session.idle"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionIdle performs a merge with any union data inside the EventEnvelope_Event, using the provided SessionIdle
func (t *EventEnvelope_Event) MergeSessionIdle(v SessionIdle) error {
	v.Type = "session.idle"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPermissionUpdated returns the union data inside the EventEnvelope_Event as a PermissionUpdated
func (t EventEnvelope_Event) AsPermissionUpdated() (PermissionUpdated, error) {
	var body PermissionUpdated
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPermissionUpdated overwrites any union data inside the EventEnvelope_Event as the provided PermissionUpdated
func (t *EventEnvelope_Event) FromPermissionUpdated(v PermissionUpdated) error {
	v.Type = "permission.updated"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePermissionUpdated performs a merge with any union data inside the EventEnvelope_Event, using the provided PermissionUpdated
func (t *EventEnvelope_Event) MergePermissionUpdated(v PermissionUpdated) error {
	v.Type = "permission.updated"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBannerEvent returns the union data inside the EventEnvelope_Event as a BannerEvent
func (t EventEnvelope_Event) AsBannerEvent() (BannerEvent, error) {
	var body BannerEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBannerEvent overwrites any union data inside the EventEnvelope_Event as the provided BannerEvent
func (t *EventEnvelope_Event) FromBannerEvent(v BannerEvent) error {
	v.Type = "banner"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBannerEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided BannerEvent
func (t *EventEnvelope_Event) MergeBannerEvent(v BannerEvent) error {
	v.Type = "banner"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserEvent returns the union data inside the EventEnvelope_Event as a UserEvent
func (t EventEnvelope_Event) AsUserEvent() (UserEvent, error) {
	var body UserEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserEvent overwrites any union data inside the EventEnvelope_Event as the provided UserEvent
func (t *EventEnvelope_Event) FromUserEvent(v UserEvent) error {
	v.Type = "user"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided UserEvent
func (t *EventEnvelope_Event) MergeUserEvent(v UserEvent) error {
	v.Type = "user"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsThinkingEvent returns the union data inside the EventEnvelope_Event as a ThinkingEvent
func (t EventEnvelope_Event) AsThinkingEvent() (ThinkingEvent, error) {
	var body ThinkingEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromThinkingEvent overwrites any union data inside the EventEnvelope_Event as the provided ThinkingEvent
func (t *EventEnvelope_Event) FromThinkingEvent(v ThinkingEvent) error {
	v.Type = "thinking"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeThinkingEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided ThinkingEvent
func (t *EventEnvelope_Event) MergeThinkingEvent(v ThinkingEvent) error {
	v.Type = "thinking"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPlanEvent returns the union data inside the EventEnvelope_Event as a PlanEvent
func (t EventEnvelope_Event) AsPlanEvent() (PlanEvent, error) {
	var body PlanEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPlanEvent overwrites any union data inside the EventEnvelope_Event as the provided PlanEvent
func (t *EventEnvelope_Event) FromPlanEvent(v PlanEvent) error {
	v.Type = "plan"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePlanEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided PlanEvent
func (t *EventEnvelope_Event) MergePlanEvent(v PlanEvent) error {
	v.Type = "plan"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsToolEvent returns the union data inside the EventEnvelope_Event as a ToolEvent
func (t EventEnvelope_Event) AsToolEvent() (ToolEvent, error) {
	var body ToolEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromToolEvent overwrites any union data inside the EventEnvelope_Event as the provided ToolEvent
func (t *EventEnvelope_Event) FromToolEvent(v ToolEvent) error {
	v.Type = "tool"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeToolEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided ToolEvent
func (t *EventEnvelope_Event) MergeToolEvent(v ToolEvent) error {
	v.Type = "tool"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsClarifyEvent returns the union data inside the EventEnvelope_Event as a ClarifyEvent
func (t EventEnvelope_Event) AsClarifyEvent() (ClarifyEvent, error) {
	var body ClarifyEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromClarifyEvent overwrites any union data inside the EventEnvelope_Event as the provided ClarifyEvent
func (t *EventEnvelope_Event) FromClarifyEvent(v ClarifyEvent) error {
	v.Type = "clarify"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeClarifyEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided ClarifyEvent
func (t *EventEnvelope_Event) MergeClarifyEvent(v ClarifyEvent) error {
	v.Type = "clarify"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFinalEvent returns the union data inside the EventEnvelope_Event as a FinalEvent
func (t EventEnvelope_Event) AsFinalEvent() (FinalEvent, error) {
	var body FinalEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFinalEvent overwrites any union data inside the EventEnvelope_Event as the provided FinalEvent
func (t *EventEnvelope_Event) FromFinalEvent(v FinalEvent) error {
	v.Type = "final"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFinalEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided FinalEvent
func (t *EventEnvelope_Event) MergeFinalEvent(v FinalEvent) error {
	v.Type = "final"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamDelta returns the union data inside the EventEnvelope_Event as a StreamDelta
func (t EventEnvelope_Event) AsStreamDelta() (StreamDelta, error) {
	var body StreamDelta
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamDelta overwrites any union data inside the EventEnvelope_Event as the provided StreamDelta
func (t *EventEnvelope_Event) FromStreamDelta(v StreamDelta) error {
	v.Type = "stream.delta"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamDelta performs a merge with any union data inside the EventEnvelope_Event, using the provided StreamDelta
func (t *EventEnvelope_Event) MergeStreamDelta(v StreamDelta) error {
	v.Type = "stream.delta"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamFinalize returns the union data inside the EventEnvelope_Event as a StreamFinalize
func (t EventEnvelope_Event) AsStreamFinalize() (StreamFinalize, error) {
	var body StreamFinalize
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamFinalize overwrites any union data inside the EventEnvelope_Event as the provided StreamFinalize
func (t *EventEnvelope_Event) FromStreamFinalize(v StreamFinalize) error {
	v.Type = "stream.finalize"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamFinalize performs a merge with any union data inside the EventEnvelope_Event, using the provided StreamFinalize
func (t *EventEnvelope_Event) MergeStreamFinalize(v StreamFinalize) error {
	v.Type = "stream.finalize"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStatusEvent returns the union data inside the EventEnvelope_Event as a StatusEvent
func (t EventEnvelope_Event) AsStatusEvent() (StatusEvent, error) {
	var body StatusEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStatusEvent overwrites any union data inside the EventEnvelope_Event as the provided StatusEvent
func (t *EventEnvelope_Event) FromStatusEvent(v StatusEvent) error {
	v.Type = "status"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStatusEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided StatusEvent
func (t *EventEnvelope_Event) MergeStatusEvent(v StatusEvent) error {
	v.Type = "status"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCognitionLoaded returns the union data inside the EventEnvelope_Event as a CognitionLoaded
func (t EventEnvelope_Event) AsCognitionLoaded() (CognitionLoaded, error) {
	var body CognitionLoaded
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCognitionLoaded overwrites any union data inside the EventEnvelope_Event as the provided CognitionLoaded
func (t *EventEnvelope_Event) FromCognitionLoaded(v CognitionLoaded) error {
	v.Type = "cognition_loaded"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCognitionLoaded performs a merge with any union data inside the EventEnvelope_Event, using the provided CognitionLoaded
func (t *EventEnvelope_Event) MergeCognitionLoaded(v CognitionLoaded) error {
	v.Type = "cognition_loaded"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCognitionOverflow returns the union data inside the EventEnvelope_Event as a CognitionOverflow
func (t EventEnvelope_Event) AsCognitionOverflow() (CognitionOverflow, error) {
	var body CognitionOverflow
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCognitionOverflow overwrites any union data inside the EventEnvelope_Event as the provided CognitionOverflow
func (t *EventEnvelope_Event) FromCognitionOverflow(v CognitionOverflow) error {
	v.Type = "cognition_overflow"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCognitionOverflow performs a merge with any union data inside the EventEnvelope_Event, using the provided CognitionOverflow
func (t *EventEnvelope_Event) MergeCognitionOverflow(v CognitionOverflow) error {
	v.Type = "cognition_overflow"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPrinciplesOverflow returns the union data inside the EventEnvelope_Event as a PrinciplesOverflow
func (t EventEnvelope_Event) AsPrinciplesOverflow() (PrinciplesOverflow, error) {
	var body PrinciplesOverflow
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPrinciplesOverflow overwrites any union data inside the EventEnvelope_Event as the provided PrinciplesOverflow
func (t *EventEnvelope_Event) FromPrinciplesOverflow(v PrinciplesOverflow) error {
	v.Type = "principles_overflow"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePrinciplesOverflow performs a merge with any union data inside the EventEnvelope_Event, using the provided PrinciplesOverflow
func (t *EventEnvelope_Event) MergePrinciplesOverflow(v PrinciplesOverflow) error {
	v.Type = "principles_overflow"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsWarningEvent returns the union data inside the EventEnvelope_Event as a WarningEvent
func (t EventEnvelope_Event) AsWarningEvent() (WarningEvent, error) {
	var body WarningEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromWarningEvent overwrites any union data inside the EventEnvelope_Event as the provided WarningEvent
func (t *EventEnvelope_Event) FromWarningEvent(v WarningEvent) error {
	v.Type = "warning"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeWarningEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided WarningEvent
func (t *EventEnvelope_Event) MergeWarningEvent(v WarningEvent) error {
	v.Type = "warning"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProbableEvent returns the union data inside the EventEnvelope_Event as a ProbableEvent
func (t EventEnvelope_Event) AsProbableEvent() (ProbableEvent, error) {
	var body ProbableEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProbableEvent overwrites any union data inside the EventEnvelope_Event as the provided ProbableEvent
func (t *EventEnvelope_Event) FromProbableEvent(v ProbableEvent) error {
	v.Type = "probable"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProbableEvent performs a merge with any union data inside the EventEnvelope_Event, using the provided ProbableEvent
func (t *EventEnvelope_Event) MergeProbableEvent(v ProbableEvent) error {
	v.Type = "probable"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBudgetUpdated returns the union data inside the EventEnvelope_Event as a BudgetUpdated
func (t EventEnvelope_Event) AsBudgetUpdated() (BudgetUpdated, error) {
	var body BudgetUpdated
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBudgetUpdated overwrites any union data inside the EventEnvelope_Event as the provided BudgetUpdated
func (t *EventEnvelope_Event) FromBudgetUpdated(v BudgetUpdated) error {
	v.Type = "budget.updated"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBudgetUpdated performs a merge with any union data inside the EventEnvelope_Event, using the provided BudgetUpdated
func (t *EventEnvelope_Event) MergeBudgetUpdated(v BudgetUpdated) error {
	v.Type = "budget.updated"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConfidenceUpdated returns the union data inside the EventEnvelope_Event as a ConfidenceUpdated
func (t EventEnvelope_Event) AsConfidenceUpdated() (ConfidenceUpdated, error) {
	var body ConfidenceUpdated
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConfidenceUpdated overwrites any union data inside the EventEnvelope_Event as the provided ConfidenceUpdated
func (t *EventEnvelope_Event) FromConfidenceUpdated(v ConfidenceUpdated) error {
	v.Type = "confidence.updated"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConfidenceUpdated performs a merge with any union data inside the EventEnvelope_Event, using the provided ConfidenceUpdated
func (t *EventEnvelope_Event) MergeConfidenceUpdated(v ConfidenceUpdated) error {
	v.Type = "confidence.updated"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGateUpdated returns the union data inside the EventEnvelope_Event as a GateUpdated
func (t EventEnvelope_Event) AsGateUpdated() (GateUpdated, error) {
	var body GateUpdated
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGateUpdated overwrites any union data inside the EventEnvelope_Event as the provided GateUpdated
func (t *EventEnvelope_Event) FromGateUpdated(v GateUpdated) error {
	v.Type = "gate.updated"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGateUpdated performs a merge with any union data inside the EventEnvelope_Event, using the provided GateUpdated
func (t *EventEnvelope_Event) MergeGateUpdated(v GateUpdated) error {
	v.Type = "gate.updated"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EventEnvelope_Event) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t EventEnvelope_Event) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "banner":
		return t.AsBannerEvent()
	case "budget.updated":
		return t.AsBudgetUpdated()
	case "clarify":
		return t.AsClarifyEvent()
	case "cognition_loaded":
		return t.AsCognitionLoaded()
	case "cognition_overflow":
		return t.AsCognitionOverflow()
	case "confidence.updated":
		return t.AsConfidenceUpdated()
	case "final":
		return t.AsFinalEvent()
	case "gate.updated":
		return t.AsGateUpdated()
	case "permission.updated":
		return t.AsPermissionUpdated()
	case "plan":
		return t.AsPlanEvent()
	case "principles_overflow":
		return t.AsPrinciplesOverflow()
	case "probable":
		return t.AsProbableEvent()
	case "server.connected":
		return t.AsServerConnected()
	case "session.idle":
		return t.AsSessionIdle()
	case "status":
		return t.AsStatusEvent()
	case "stream.delta":
		return t.AsStreamDelta()
	case "stream.finalize":
		return t.AsStreamFinalize()
	case "thinking":
		return t.AsThinkingEvent()
	case "tool":
		return t.AsToolEvent()
	case "user":
		return t.AsUserEvent()
	case "warning":
		return t.AsWarningEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t EventEnvelope_Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *EventEnvelope_Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
