"""E2E runner for subprocess-driven Voss CLI tests.

CliRunner invokes `python -m voss.cli <args>` from a tmp project root with a
deterministic env that:

  1. Registers a StubProvider in ``voss_runtime`` (mirrors
     ``tests/examples/helpers.deterministic_subprocess_env``).
  2. Monkey-patches ``voss.harness.cli._resolve_auth_or_die`` to return the
     StubProvider directly, bypassing the live OAuth / API-key resolution
     that would otherwise exit 2 in CI without creds.

Both patches are installed via a generated ``sitecustomize.py`` prepended to
``PYTHONPATH`` so any child process imports land on the deterministic stub.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import textwrap
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Iterator

import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------


@dataclass
class Result:
    """Captured result of one CLI invocation."""

    returncode: int
    stdout: str
    stderr: str
    args: list[str]
    cwd: Path

    @property
    def output(self) -> str:
        """Convenience: stdout + stderr concatenated."""
        return self.stdout + self.stderr

    def json_payloads(self) -> list[dict[str, Any]]:
        """Parse NDJSON lines from stdout.

        Lines that fail to parse are skipped silently. Callers asserting a
        specific shape should also assert non-empty result.
        """
        out: list[dict[str, Any]] = []
        for line in self.stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        return out

    def first_json(self) -> dict[str, Any]:
        """First parseable JSON line in stdout. Raises if none."""
        payloads = self.json_payloads()
        if not payloads:
            raise AssertionError(
                f"no JSON payload in stdout. raw stdout:\n{self.stdout!r}"
            )
        return payloads[0]


# ---------------------------------------------------------------------------
# Sitecustomize source
# ---------------------------------------------------------------------------


_SITECUSTOMIZE_TEMPLATE = '''
"""Auto-generated by tests/e2e/runner.py — DO NOT EDIT."""
import json as _json
import os as _os

import voss_runtime as _voss_runtime
from voss_runtime import StubProvider as _StubProvider
from voss_runtime import configure as _configure

# Load stub responses from env (JSON object keyed by message-fingerprint)
# falling back to a single default response if not provided.
_default = _os.environ.get("VOSS_TEST_STUB_RESPONSE", "stub-response")
_responses_raw = _os.environ.get("VOSS_TEST_STUB_RESPONSES")
_responses = _json.loads(_responses_raw) if _responses_raw else {{}}

_stub = _StubProvider(default_response=_default, responses=_responses)
_voss_runtime.providers.register("__stub__", _stub)
_configure(default_model="__stub__")

# Patch harness auth resolver so `voss do/chat/edit/resume/skill run/agent
# spawn` use the stub provider instead of dying on missing creds.
try:
    from voss.harness import auth as _auth
    from voss.harness import cli as _hcli

    def _stub_resolve(preference, *args, **kwargs):  # type: ignore[no-redef]
        # Mirror _resolve_auth_or_die(preference, *, announce=...); absorb any
        # extra kwargs so signature drift in the real resolver can't break e2e.
        return (
            _auth.Resolution(source="env-anthropic", detail="stub-e2e"),
            _stub,
        )

    _hcli._resolve_auth_or_die = _stub_resolve
except Exception:  # noqa: BLE001 — harness may not be importable in some contexts
    pass

{extra}
'''


def _build_sitecustomize(extra: str = "") -> str:
    return _SITECUSTOMIZE_TEMPLATE.format(extra=textwrap.dedent(extra))


# ---------------------------------------------------------------------------
# CliRunner
# ---------------------------------------------------------------------------


@dataclass
class CliRunner:
    """Invokes `python -m voss.cli <args>` in a deterministic subprocess.

    Each `run()` call starts a fresh process. State that the harness writes
    under cwd/.voss/ or under $XDG_STATE_HOME persists between calls in the
    same fixture (intentional — supports session round-trip tests).
    """

    project_root: Path
    state_home: Path
    default_response: str = "stub-response"
    responses: dict[str, str] = field(default_factory=dict)
    extra_sitecustomize: str = ""

    def __post_init__(self) -> None:
        self.project_root = Path(self.project_root).resolve()
        self.state_home = Path(self.state_home).resolve()
        self._stub_dir = self.state_home / "_voss_stub"
        self._stub_dir.mkdir(parents=True, exist_ok=True)
        (self._stub_dir / "sitecustomize.py").write_text(
            _build_sitecustomize(self.extra_sitecustomize)
        )

    def env(self, **overrides: str) -> dict[str, str]:
        """Build the deterministic env dict."""
        env = dict(os.environ)
        # Strip any inherited live creds — we want stub-only behavior.
        for k in ("ANTHROPIC_API_KEY", "OPENAI_API_KEY"):
            env.pop(k, None)
        env["XDG_STATE_HOME"] = str(self.state_home)
        env["XDG_CONFIG_HOME"] = str(self.state_home / "config")
        env["HOME"] = str(self.state_home / "home")
        env["VOSS_TEST_STUB_RESPONSE"] = self.default_response
        if self.responses:
            env["VOSS_TEST_STUB_RESPONSES"] = json.dumps(self.responses)
        # Block accidental HF Hub / transformers downloads — they make
        # vacuum / memory CLI tests hang for 30s and bloat CI traffic.
        env["HF_HUB_OFFLINE"] = "1"
        env["TRANSFORMERS_OFFLINE"] = "1"
        existing = env.get("PYTHONPATH", "")
        parts = [str(self._stub_dir), str(REPO_ROOT)]
        if existing:
            parts.append(existing)
        env["PYTHONPATH"] = os.pathsep.join(parts)
        env.update(overrides)
        return env

    def run(
        self,
        *args: str,
        stdin: str | None = None,
        timeout: float = 30.0,
        env_overrides: dict[str, str] | None = None,
        cwd: Path | None = None,
    ) -> Result:
        """Run `voss <args>` and return a Result."""
        argv = [sys.executable, "-m", "voss.cli", *args]
        # Default to empty-string stdin so the harness's "piped stdin" branch
        # (sys.stdin.isatty() == False under subprocess) appends nothing.
        proc = subprocess.run(
            argv,
            cwd=str(cwd or self.project_root),
            env=self.env(**(env_overrides or {})),
            input="" if stdin is None else stdin,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return Result(
            returncode=proc.returncode,
            stdout=proc.stdout,
            stderr=proc.stderr,
            args=list(args),
            cwd=Path(cwd or self.project_root),
        )


# ---------------------------------------------------------------------------
# Parametrize helpers
# ---------------------------------------------------------------------------


PERM_MODES = ("plan", "edit", "auto")


def mode_matrix(*modes: str):
    """`@mode_matrix()` parametrizes over permission modes.

    Default (`mode_matrix()`) covers all three modes. Pass explicit modes to
    restrict, e.g. `mode_matrix("plan", "edit")`.
    """
    chosen = modes or PERM_MODES
    return pytest.mark.parametrize("mode", chosen)


# ---------------------------------------------------------------------------
# JSON shape validation
# ---------------------------------------------------------------------------


def assert_json_shape(payload: dict[str, Any], schema: type) -> Any:
    """Validate `payload` against a pydantic BaseModel `schema`.

    Returns the parsed model instance. Re-raises pydantic ValidationError as
    AssertionError for cleaner pytest reporting.
    """
    try:
        return schema.model_validate(payload)
    except Exception as e:  # noqa: BLE001 — surface as test failure
        raise AssertionError(
            f"JSON payload does not match {schema.__name__}: {e}\n"
            f"payload: {payload!r}"
        ) from e


# ---------------------------------------------------------------------------
# Golden transcript record/replay
# ---------------------------------------------------------------------------


_TRANSCRIPTS_DIR = Path(__file__).resolve().parent / "transcripts"


def record_or_assert_transcript(
    name: str,
    payload: Any,
    *,
    update: bool,
) -> None:
    """Compare `payload` to the recorded transcript at transcripts/<name>.json.

    If `update` is True (driven by the `--update-transcripts` pytest flag),
    overwrite the file. Otherwise diff and raise AssertionError on mismatch.
    """
    path = _TRANSCRIPTS_DIR / f"{name}.json"
    serialized = json.dumps(payload, indent=2, sort_keys=True, default=str)
    if update or not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(serialized + "\n")
        return
    expected = path.read_text().rstrip("\n")
    if expected != serialized:
        raise AssertionError(
            f"transcript mismatch for {name!r}.\n"
            f"--- expected ({path}) ---\n{expected}\n"
            f"--- actual ---\n{serialized}\n"
            f"run with --update-transcripts to refresh."
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def new_session_id() -> str:
    """Stable-format session id (mirrors SessionRecord.new shape)."""
    return uuid.uuid4().hex[:12]


def iter_sessions(project_root: Path) -> Iterator[Path]:
    """Yield session JSON files under <project_root>/.voss/sessions/."""
    sessions_dir = project_root / ".voss" / "sessions"
    if not sessions_dir.is_dir():
        return
    yield from sorted(sessions_dir.glob("*.json"))
