"""
Stubs covering COG requirements:
COG-01, COG-02, COG-03, COG-04, COG-05, COG-06, COG-07, COG-08,
COG-09, COG-10, COG-11, COG-12, COG-13, COG-14
"""
import pytest


@pytest.mark.skip(reason="Wave 2 — pending plan M2-04")
def test_analyze_writes_project_json() -> None:
    pass


@pytest.mark.skip(reason="Wave 2 — pending plan M2-04")
def test_architecture_md_frontmatter_well_formed() -> None:
    pass


@pytest.mark.skip(reason="Wave 1 — pending plan M2-01")
def test_load_parses_frontmatter() -> None:
    pass


@pytest.mark.skip(reason="Wave 1 — pending plan M2-01")
def test_drift_commits_threshold() -> None:
    pass


@pytest.mark.skip(reason="Wave 1 — pending plan M2-01")
def test_drift_file_count_threshold() -> None:
    pass


@pytest.mark.skip(reason="Wave 1 — pending plan M2-01")
def test_drift_days_threshold() -> None:
    pass


@pytest.mark.skip(reason="Wave 1 — pending plan M2-01")
def test_plan_filename_and_frontmatter() -> None:
    pass


@pytest.mark.skip(reason="Wave 1 — pending plan M2-01")
def test_reserve_filename_collision() -> None:
    pass


@pytest.mark.skip(reason="Wave 2 — pending plan M2-03")
def test_decision_frontmatter() -> None:
    pass


@pytest.mark.skip(reason="Wave 1 — pending plan M2-01")
def test_repo_idx_schema() -> None:
    pass


@pytest.mark.skip(reason="Wave 1 — pending plan M2-01")
def test_gitignore_idempotent() -> None:
    pass


@pytest.mark.skip(reason="Wave 2 — pending plan M2-04")
def test_voss_gitignore_autogenerated() -> None:
    pass


@pytest.mark.skip(reason="Wave 2 — pending plan M2-04")
def test_analyze_invokes_natural_language_route() -> None:
    pass


@pytest.mark.skip(reason="Wave 2 — pending plan M2-04")
def test_analyze_emits_project_root_gitignore_append() -> None:
    pass
