// GENERATED by scripts/generate_sdk_events.py from contracts/events.schema.json.
// Do not edit by hand. Regenerate with: .venv/bin/python scripts/generate_sdk_events.py

#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`Alternative`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"Alternative\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"probability\","]
#[doc = "    \"text\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"probability\": {"]
#[doc = "      \"title\": \"Probability\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"text\": {"]
#[doc = "      \"title\": \"Text\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct Alternative {
    pub probability: f64,
    pub text: ::std::string::String,
}
#[doc = "`BannerEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"BannerEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"cwd\","]
#[doc = "    \"git\","]
#[doc = "    \"model\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"cwd\": {"]
#[doc = "      \"title\": \"Cwd\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"git\": {"]
#[doc = "      \"title\": \"Git\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"model\": {"]
#[doc = "      \"title\": \"Model\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"banner\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"banner\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct BannerEvent {
    pub cwd: ::std::string::String,
    pub git: ::std::string::String,
    pub model: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`BudgetUpdated`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"BudgetUpdated\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"limit\","]
#[doc = "    \"remaining\","]
#[doc = "    \"session_id\","]
#[doc = "    \"spent\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"limit\": {"]
#[doc = "      \"title\": \"Limit\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"remaining\": {"]
#[doc = "      \"title\": \"Remaining\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"title\": \"Session Id\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"spent\": {"]
#[doc = "      \"title\": \"Spent\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"budget.updated\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"budget.updated\""]
#[doc = "    },"]
#[doc = "    \"unit\": {"]
#[doc = "      \"title\": \"Unit\","]
#[doc = "      \"default\": \"tokens\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"enum\": ["]
#[doc = "        \"tokens\","]
#[doc = "        \"usd\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct BudgetUpdated {
    pub limit: f64,
    pub remaining: f64,
    pub session_id: ::std::string::String,
    pub spent: f64,
    #[serde(default = "defaults::budget_updated_unit")]
    pub unit: Unit,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`ClarifyEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"ClarifyEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"confidence\","]
#[doc = "    \"question\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"confidence\": {"]
#[doc = "      \"title\": \"Confidence\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"question\": {"]
#[doc = "      \"title\": \"Question\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"clarify\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"clarify\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ClarifyEvent {
    pub confidence: f64,
    pub question: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`CognitionLoaded`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"CognitionLoaded\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"architecture_tokens\","]
#[doc = "    \"constraints_count\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"architecture_tokens\": {"]
#[doc = "      \"title\": \"Architecture Tokens\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"constraints_count\": {"]
#[doc = "      \"title\": \"Constraints Count\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"decisions_loaded\": {"]
#[doc = "      \"title\": \"Decisions Loaded\","]
#[doc = "      \"default\": 0,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"plans_loaded\": {"]
#[doc = "      \"title\": \"Plans Loaded\","]
#[doc = "      \"default\": 0,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"cognition_loaded\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"cognition_loaded\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct CognitionLoaded {
    pub architecture_tokens: i64,
    pub constraints_count: i64,
    #[serde(default)]
    pub decisions_loaded: i64,
    #[serde(default)]
    pub plans_loaded: i64,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`CognitionOverflow`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"CognitionOverflow\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"architecture_tokens\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"architecture_tokens\": {"]
#[doc = "      \"title\": \"Architecture Tokens\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"budget\": {"]
#[doc = "      \"title\": \"Budget\","]
#[doc = "      \"default\": 6000,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"cognition_overflow\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"cognition_overflow\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct CognitionOverflow {
    pub architecture_tokens: i64,
    #[serde(default = "defaults::default_u64::<i64, 6000>")]
    pub budget: i64,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`ConfidenceUpdated`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"ConfidenceUpdated\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"score\","]
#[doc = "    \"session_id\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"message_id\": {"]
#[doc = "      \"title\": \"Message Id\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"anyOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"score\": {"]
#[doc = "      \"title\": \"Score\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"title\": \"Session Id\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"confidence.updated\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"confidence.updated\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ConfidenceUpdated {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub message_id: ::std::option::Option<::std::string::String>,
    pub score: f64,
    pub session_id: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`Event`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"Event\","]
#[doc = "  \"oneOf\": ["]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/ServerConnected\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/SessionIdle\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/PermissionUpdated\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/BannerEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/UserEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/ThinkingEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/PlanEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/ToolEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/ClarifyEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/FinalEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/StreamDelta\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/StreamFinalize\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/StatusEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/CognitionLoaded\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/CognitionOverflow\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/PrinciplesOverflow\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/WarningEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/ProbableEvent\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/BudgetUpdated\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/ConfidenceUpdated\""]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"$ref\": \"#/components/schemas/GateUpdated\""]
#[doc = "    }"]
#[doc = "  ],"]
#[doc = "  \"discriminator\": {"]
#[doc = "    \"mapping\": {"]
#[doc = "      \"banner\": \"#/components/schemas/BannerEvent\","]
#[doc = "      \"budget.updated\": \"#/components/schemas/BudgetUpdated\","]
#[doc = "      \"clarify\": \"#/components/schemas/ClarifyEvent\","]
#[doc = "      \"cognition_loaded\": \"#/components/schemas/CognitionLoaded\","]
#[doc = "      \"cognition_overflow\": \"#/components/schemas/CognitionOverflow\","]
#[doc = "      \"confidence.updated\": \"#/components/schemas/ConfidenceUpdated\","]
#[doc = "      \"final\": \"#/components/schemas/FinalEvent\","]
#[doc = "      \"gate.updated\": \"#/components/schemas/GateUpdated\","]
#[doc = "      \"permission.updated\": \"#/components/schemas/PermissionUpdated\","]
#[doc = "      \"plan\": \"#/components/schemas/PlanEvent\","]
#[doc = "      \"principles_overflow\": \"#/components/schemas/PrinciplesOverflow\","]
#[doc = "      \"probable\": \"#/components/schemas/ProbableEvent\","]
#[doc = "      \"server.connected\": \"#/components/schemas/ServerConnected\","]
#[doc = "      \"session.idle\": \"#/components/schemas/SessionIdle\","]
#[doc = "      \"status\": \"#/components/schemas/StatusEvent\","]
#[doc = "      \"stream.delta\": \"#/components/schemas/StreamDelta\","]
#[doc = "      \"stream.finalize\": \"#/components/schemas/StreamFinalize\","]
#[doc = "      \"thinking\": \"#/components/schemas/ThinkingEvent\","]
#[doc = "      \"tool\": \"#/components/schemas/ToolEvent\","]
#[doc = "      \"user\": \"#/components/schemas/UserEvent\","]
#[doc = "      \"warning\": \"#/components/schemas/WarningEvent\""]
#[doc = "    },"]
#[doc = "    \"propertyName\": \"type\""]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(tag = "type")]
pub enum AgentEvent {
    #[serde(rename = "server.connected")]
    ServerConnected(ServerConnected),
    #[serde(rename = "session.idle")]
    SessionIdle(SessionIdle),
    #[serde(rename = "permission.updated")]
    PermissionUpdated(PermissionUpdated),
    #[serde(rename = "banner")]
    BannerEvent(BannerEvent),
    #[serde(rename = "user")]
    UserEvent(UserEvent),
    #[serde(rename = "thinking")]
    ThinkingEvent(ThinkingEvent),
    #[serde(rename = "plan")]
    PlanEvent(PlanEvent),
    #[serde(rename = "tool")]
    ToolEvent(ToolEvent),
    #[serde(rename = "clarify")]
    ClarifyEvent(ClarifyEvent),
    #[serde(rename = "final")]
    FinalEvent(FinalEvent),
    #[serde(rename = "stream.delta")]
    StreamDelta(StreamDelta),
    #[serde(rename = "stream.finalize")]
    StreamFinalize(StreamFinalize),
    #[serde(rename = "status")]
    StatusEvent(StatusEvent),
    #[serde(rename = "cognition_loaded")]
    CognitionLoaded(CognitionLoaded),
    #[serde(rename = "cognition_overflow")]
    CognitionOverflow(CognitionOverflow),
    #[serde(rename = "principles_overflow")]
    PrinciplesOverflow(PrinciplesOverflow),
    #[serde(rename = "warning")]
    WarningEvent(WarningEvent),
    #[serde(rename = "probable")]
    ProbableEvent(ProbableEvent),
    #[serde(rename = "budget.updated")]
    BudgetUpdated(BudgetUpdated),
    #[serde(rename = "confidence.updated")]
    ConfidenceUpdated(ConfidenceUpdated),
    #[serde(rename = "gate.updated")]
    GateUpdated(GateUpdated),
}
impl ::std::convert::From<ServerConnected> for AgentEvent {
    fn from(value: ServerConnected) -> Self {
        Self::ServerConnected(value)
    }
}
impl ::std::convert::From<SessionIdle> for AgentEvent {
    fn from(value: SessionIdle) -> Self {
        Self::SessionIdle(value)
    }
}
impl ::std::convert::From<PermissionUpdated> for AgentEvent {
    fn from(value: PermissionUpdated) -> Self {
        Self::PermissionUpdated(value)
    }
}
impl ::std::convert::From<BannerEvent> for AgentEvent {
    fn from(value: BannerEvent) -> Self {
        Self::BannerEvent(value)
    }
}
impl ::std::convert::From<UserEvent> for AgentEvent {
    fn from(value: UserEvent) -> Self {
        Self::UserEvent(value)
    }
}
impl ::std::convert::From<ThinkingEvent> for AgentEvent {
    fn from(value: ThinkingEvent) -> Self {
        Self::ThinkingEvent(value)
    }
}
impl ::std::convert::From<PlanEvent> for AgentEvent {
    fn from(value: PlanEvent) -> Self {
        Self::PlanEvent(value)
    }
}
impl ::std::convert::From<ToolEvent> for AgentEvent {
    fn from(value: ToolEvent) -> Self {
        Self::ToolEvent(value)
    }
}
impl ::std::convert::From<ClarifyEvent> for AgentEvent {
    fn from(value: ClarifyEvent) -> Self {
        Self::ClarifyEvent(value)
    }
}
impl ::std::convert::From<FinalEvent> for AgentEvent {
    fn from(value: FinalEvent) -> Self {
        Self::FinalEvent(value)
    }
}
impl ::std::convert::From<StreamDelta> for AgentEvent {
    fn from(value: StreamDelta) -> Self {
        Self::StreamDelta(value)
    }
}
impl ::std::convert::From<StreamFinalize> for AgentEvent {
    fn from(value: StreamFinalize) -> Self {
        Self::StreamFinalize(value)
    }
}
impl ::std::convert::From<StatusEvent> for AgentEvent {
    fn from(value: StatusEvent) -> Self {
        Self::StatusEvent(value)
    }
}
impl ::std::convert::From<CognitionLoaded> for AgentEvent {
    fn from(value: CognitionLoaded) -> Self {
        Self::CognitionLoaded(value)
    }
}
impl ::std::convert::From<CognitionOverflow> for AgentEvent {
    fn from(value: CognitionOverflow) -> Self {
        Self::CognitionOverflow(value)
    }
}
impl ::std::convert::From<PrinciplesOverflow> for AgentEvent {
    fn from(value: PrinciplesOverflow) -> Self {
        Self::PrinciplesOverflow(value)
    }
}
impl ::std::convert::From<WarningEvent> for AgentEvent {
    fn from(value: WarningEvent) -> Self {
        Self::WarningEvent(value)
    }
}
impl ::std::convert::From<ProbableEvent> for AgentEvent {
    fn from(value: ProbableEvent) -> Self {
        Self::ProbableEvent(value)
    }
}
impl ::std::convert::From<BudgetUpdated> for AgentEvent {
    fn from(value: BudgetUpdated) -> Self {
        Self::BudgetUpdated(value)
    }
}
impl ::std::convert::From<ConfidenceUpdated> for AgentEvent {
    fn from(value: ConfidenceUpdated) -> Self {
        Self::ConfidenceUpdated(value)
    }
}
impl ::std::convert::From<GateUpdated> for AgentEvent {
    fn from(value: GateUpdated) -> Self {
        Self::GateUpdated(value)
    }
}
#[doc = "OpenAPI schema anchor (H1.14).\n\nForced into the OpenAPI components so a typed client codegens a tagged\nenum over the full event union, even though no route returns it directly."]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"EventEnvelope\","]
#[doc = "  \"description\": \"OpenAPI schema anchor (H1.14).\\n\\nForced into the OpenAPI components so a typed client codegens a tagged\\nenum over the full event union, even though no route returns it directly.\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"event\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"event\": {"]
#[doc = "      \"title\": \"Event\","]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/ServerConnected\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/SessionIdle\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/PermissionUpdated\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/BannerEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/UserEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/ThinkingEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/PlanEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/ToolEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/ClarifyEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/FinalEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/StreamDelta\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/StreamFinalize\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/StatusEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/CognitionLoaded\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/CognitionOverflow\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/PrinciplesOverflow\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/WarningEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/ProbableEvent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/BudgetUpdated\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/ConfidenceUpdated\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/components/schemas/GateUpdated\""]
#[doc = "        }"]
#[doc = "      ],"]
#[doc = "      \"discriminator\": {"]
#[doc = "        \"mapping\": {"]
#[doc = "          \"banner\": \"#/components/schemas/BannerEvent\","]
#[doc = "          \"budget.updated\": \"#/components/schemas/BudgetUpdated\","]
#[doc = "          \"clarify\": \"#/components/schemas/ClarifyEvent\","]
#[doc = "          \"cognition_loaded\": \"#/components/schemas/CognitionLoaded\","]
#[doc = "          \"cognition_overflow\": \"#/components/schemas/CognitionOverflow\","]
#[doc = "          \"confidence.updated\": \"#/components/schemas/ConfidenceUpdated\","]
#[doc = "          \"final\": \"#/components/schemas/FinalEvent\","]
#[doc = "          \"gate.updated\": \"#/components/schemas/GateUpdated\","]
#[doc = "          \"permission.updated\": \"#/components/schemas/PermissionUpdated\","]
#[doc = "          \"plan\": \"#/components/schemas/PlanEvent\","]
#[doc = "          \"principles_overflow\": \"#/components/schemas/PrinciplesOverflow\","]
#[doc = "          \"probable\": \"#/components/schemas/ProbableEvent\","]
#[doc = "          \"server.connected\": \"#/components/schemas/ServerConnected\","]
#[doc = "          \"session.idle\": \"#/components/schemas/SessionIdle\","]
#[doc = "          \"status\": \"#/components/schemas/StatusEvent\","]
#[doc = "          \"stream.delta\": \"#/components/schemas/StreamDelta\","]
#[doc = "          \"stream.finalize\": \"#/components/schemas/StreamFinalize\","]
#[doc = "          \"thinking\": \"#/components/schemas/ThinkingEvent\","]
#[doc = "          \"tool\": \"#/components/schemas/ToolEvent\","]
#[doc = "          \"user\": \"#/components/schemas/UserEvent\","]
#[doc = "          \"warning\": \"#/components/schemas/WarningEvent\""]
#[doc = "        },"]
#[doc = "        \"propertyName\": \"type\""]
#[doc = "      }"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct EventEnvelope {
    pub event: AgentEvent,
}
#[doc = "`FinalEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"FinalEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"confidence\","]
#[doc = "    \"cost_usd\","]
#[doc = "    \"text\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"confidence\": {"]
#[doc = "      \"title\": \"Confidence\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"cost_usd\": {"]
#[doc = "      \"title\": \"Cost Usd\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"text\": {"]
#[doc = "      \"title\": \"Text\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"final\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"final\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct FinalEvent {
    pub confidence: f64,
    pub cost_usd: f64,
    pub text: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`GateUpdated`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"GateUpdated\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"decision\","]
#[doc = "    \"gate\","]
#[doc = "    \"session_id\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"decision\": {"]
#[doc = "      \"title\": \"Decision\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"gate\": {"]
#[doc = "      \"title\": \"Gate\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"title\": \"Session Id\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"gate.updated\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"gate.updated\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct GateUpdated {
    pub decision: ::std::string::String,
    pub gate: ::std::string::String,
    pub session_id: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`PermissionUpdated`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"PermissionUpdated\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"id\","]
#[doc = "    \"tool_name\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"args\": {"]
#[doc = "      \"title\": \"Args\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"additionalProperties\": true"]
#[doc = "    },"]
#[doc = "    \"dimension\": {"]
#[doc = "      \"title\": \"Dimension\","]
#[doc = "      \"default\": \"tool\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"id\": {"]
#[doc = "      \"title\": \"Id\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"tool_name\": {"]
#[doc = "      \"title\": \"Tool Name\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"permission.updated\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"permission.updated\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct PermissionUpdated {
    #[serde(default, skip_serializing_if = "::serde_json::Map::is_empty")]
    pub args: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    #[serde(default = "defaults::permission_updated_dimension")]
    pub dimension: ::std::string::String,
    pub id: ::std::string::String,
    pub tool_name: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`PlanEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"PlanEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"confidence\","]
#[doc = "    \"cost_usd\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"confidence\": {"]
#[doc = "      \"title\": \"Confidence\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"cost_usd\": {"]
#[doc = "      \"title\": \"Cost Usd\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"steps\": {"]
#[doc = "      \"title\": \"Steps\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/components/schemas/PlanStep\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"plan\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"plan\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct PlanEvent {
    pub confidence: f64,
    pub cost_usd: f64,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub steps: ::std::vec::Vec<PlanStep>,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`PlanStep`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"PlanStep\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"name\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"args\": {"]
#[doc = "      \"title\": \"Args\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"additionalProperties\": true"]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct PlanStep {
    #[serde(default, skip_serializing_if = "::serde_json::Map::is_empty")]
    pub args: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    pub name: ::std::string::String,
}
#[doc = "`PrinciplesOverflow`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"PrinciplesOverflow\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"principles_tokens\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"budget\": {"]
#[doc = "      \"title\": \"Budget\","]
#[doc = "      \"default\": 1000,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"principles_tokens\": {"]
#[doc = "      \"title\": \"Principles Tokens\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"principles_overflow\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"principles_overflow\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct PrinciplesOverflow {
    #[serde(default = "defaults::default_u64::<i64, 1000>")]
    pub budget: i64,
    pub principles_tokens: i64,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`ProbableEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"ProbableEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"probability\","]
#[doc = "    \"text\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"alternatives\": {"]
#[doc = "      \"title\": \"Alternatives\","]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/components/schemas/Alternative\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"probability\": {"]
#[doc = "      \"title\": \"Probability\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"text\": {"]
#[doc = "      \"title\": \"Text\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"probable\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"probable\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ProbableEvent {
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub alternatives: ::std::vec::Vec<Alternative>,
    pub probability: f64,
    pub text: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`ServerConnected`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"ServerConnected\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"server.connected\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"server.connected\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ServerConnected {
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`SessionIdle`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"SessionIdle\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"session_id\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"session_id\": {"]
#[doc = "      \"title\": \"Session Id\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"session.idle\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"session.idle\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct SessionIdle {
    pub session_id: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`StatusEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"StatusEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"cost_usd\","]
#[doc = "    \"ctx_pct\","]
#[doc = "    \"model\","]
#[doc = "    \"tokens\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"cost_usd\": {"]
#[doc = "      \"title\": \"Cost Usd\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"ctx_pct\": {"]
#[doc = "      \"title\": \"Ctx Pct\","]
#[doc = "      \"type\": \"number\""]
#[doc = "    },"]
#[doc = "    \"model\": {"]
#[doc = "      \"title\": \"Model\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"tokens\": {"]
#[doc = "      \"title\": \"Tokens\","]
#[doc = "      \"type\": \"integer\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"status\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"status\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct StatusEvent {
    pub cost_usd: f64,
    pub ctx_pct: f64,
    pub model: ::std::string::String,
    pub tokens: i64,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`StreamDelta`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"StreamDelta\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"text\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"text\": {"]
#[doc = "      \"title\": \"Text\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"stream.delta\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"stream.delta\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct StreamDelta {
    pub text: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`StreamFinalize`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"StreamFinalize\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"role\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"confidence\": {"]
#[doc = "      \"title\": \"Confidence\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"anyOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"number\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"cost_usd\": {"]
#[doc = "      \"title\": \"Cost Usd\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"anyOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"number\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"role\": {"]
#[doc = "      \"title\": \"Role\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"timestamp\": {"]
#[doc = "      \"title\": \"Timestamp\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"anyOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"string\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"stream.finalize\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"stream.finalize\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct StreamFinalize {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub confidence: ::std::option::Option<f64>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub cost_usd: ::std::option::Option<f64>,
    pub role: ::std::string::String,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub timestamp: ::std::option::Option<::std::string::String>,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`ThinkingEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"ThinkingEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"label\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"label\": {"]
#[doc = "      \"title\": \"Label\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"thinking\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"thinking\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ThinkingEvent {
    pub label: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`ToolEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"ToolEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"name\","]
#[doc = "    \"state\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"args\": {"]
#[doc = "      \"title\": \"Args\","]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"additionalProperties\": true"]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"title\": \"Name\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"state\": {"]
#[doc = "      \"title\": \"State\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"summary\": {"]
#[doc = "      \"title\": \"Summary\","]
#[doc = "      \"default\": \"\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"tool\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"tool\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ToolEvent {
    #[serde(default, skip_serializing_if = "::serde_json::Map::is_empty")]
    pub args: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    pub name: ::std::string::String,
    pub state: ::std::string::String,
    #[serde(default)]
    pub summary: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`Unit`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"Unit\","]
#[doc = "  \"default\": \"tokens\","]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"tokens\","]
#[doc = "    \"usd\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum Unit {
    #[serde(rename = "tokens")]
    Tokens,
    #[serde(rename = "usd")]
    Usd,
}
impl ::std::fmt::Display for Unit {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Tokens => f.write_str("tokens"),
            Self::Usd => f.write_str("usd"),
        }
    }
}
impl ::std::str::FromStr for Unit {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "tokens" => Ok(Self::Tokens),
            "usd" => Ok(Self::Usd),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for Unit {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for Unit {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for Unit {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::default::Default for Unit {
    fn default() -> Self {
        Unit::Tokens
    }
}
#[doc = "`UserEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"UserEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"task\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"task\": {"]
#[doc = "      \"title\": \"Task\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"user\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"user\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct UserEvent {
    pub task: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = "`WarningEvent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"WarningEvent\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"message\","]
#[doc = "    \"type\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"message\": {"]
#[doc = "      \"title\": \"Message\","]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"type\": {"]
#[doc = "      \"title\": \"Type\","]
#[doc = "      \"default\": \"warning\","]
#[doc = "      \"type\": \"string\","]
#[doc = "      \"const\": \"warning\""]
#[doc = "    },"]
#[doc = "    \"v\": {"]
#[doc = "      \"title\": \"V\","]
#[doc = "      \"default\": 1,"]
#[doc = "      \"type\": \"integer\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct WarningEvent {
    pub message: ::std::string::String,
    #[serde(default = "defaults::default_u64::<i64, 1>")]
    pub v: i64,
}
#[doc = r" Generation of default values for serde."]
pub mod defaults {
    pub(super) fn default_u64<T, const V: u64>() -> T
    where
        T: ::std::convert::TryFrom<u64>,
        <T as ::std::convert::TryFrom<u64>>::Error: ::std::fmt::Debug,
    {
        T::try_from(V).unwrap()
    }
    pub(super) fn budget_updated_unit() -> super::Unit {
        super::Unit::Tokens
    }
    pub(super) fn permission_updated_dimension() -> ::std::string::String {
        "tool".to_string()
    }
}
