"""Generate voss-sdk event types from the exported event contract."""

from __future__ import annotations

import argparse
import difflib
import json
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "contracts" / "events.schema.json"
TARGET = ROOT / "crates" / "voss-sdk" / "src" / "types" / "events.rs"
HEADER = """// GENERATED by scripts/generate_sdk_events.py from contracts/events.schema.json.
// Do not edit by hand. Regenerate with: .venv/bin/python scripts/generate_sdk_events.py

"""


def _event_mapping() -> dict[str, str]:
    schema = json.loads(SCHEMA.read_text())
    mapping = schema["properties"]["event"]["discriminator"]["mapping"]
    by_type: dict[str, str] = {}
    for wire_name, ref in mapping.items():
        by_type[ref.rsplit("/", 1)[-1]] = wire_name
    return by_type


def _run_typify(output: Path) -> None:
    subprocess.run(
        [
            "cargo",
            "typify",
            "-B",
            "-d",
            "Clone",
            "-d",
            "Debug",
            "-o",
            str(output),
            str(SCHEMA),
        ],
        cwd=ROOT,
        check=True,
    )


def _postprocess(generated: str) -> str:
    generated = generated.replace(
        "#[serde(untagged)]\npub enum Event {",
        "#[serde(tag = \"type\")]\npub enum AgentEvent {",
    )
    generated = generated.replace("pub event: Event,", "pub event: AgentEvent,")
    generated = generated.replace(" for Event {", " for AgentEvent {")
    generated = generated.replace(
        '    #[serde(rename = "type")]\n'
        "    pub type_: ::std::string::String,\n",
        "",
    )

    for type_name, wire_name in _event_mapping().items():
        variant = f"    {type_name}({type_name}),"
        generated = generated.replace(
            variant,
            f"    #[serde(rename = \"{wire_name}\")]\n{variant}",
        )

    if "#[serde(untagged)]" in generated:
        raise RuntimeError("generated event union is still untagged")
    if "pub enum AgentEvent" not in generated:
        raise RuntimeError("generated AgentEvent enum was not produced")

    return HEADER + generated


def _generate() -> str:
    with tempfile.TemporaryDirectory() as tmp:
        raw = Path(tmp) / "events.rs"
        processed = Path(tmp) / "events.processed.rs"
        _run_typify(raw)
        processed.write_text(_postprocess(raw.read_text()))
        subprocess.run(["rustfmt", str(processed)], cwd=ROOT, check=True)
        return processed.read_text()


def _check(expected: str) -> int:
    actual = TARGET.read_text()
    if actual == expected:
        return 0

    diff = "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(TARGET),
            tofile="generated",
        )
    )
    print(diff)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = _generate()
    if args.check:
        return _check(generated)

    TARGET.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
